version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=my_cluster
      #- discovery.seed_hosts=node2,node3
      - cluster.initial_master_nodes=elasticsearch,node2,node3
      #- discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk-network
  node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: node2
    environment:
      - node.name=node2
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=my_cluster

  node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: node3
    environment:
      - node.name=node3
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=my_cluster
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk-network

volumes:
  elasticsearch-data:

networks:
  elk-network:
